version: 2.1

parameters:
  new_openssl_commit:
    type: boolean
    default: false

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

jobs:
  ubuntu_x64_xbuild:
    description: Building and pushing OQS performance testing multiarch Docker image that depend on OQS-OpenSSL
    docker:
      - image: cimg/base:stable
#      - image: openquantumsafe/ci-ubuntu-focal-x86_64:latest
#        auth:
#          username: $DOCKER_LOGIN
#          password: $DOCKER_PASSWORD
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - setup_remote_docker:
          version: 19.03.14
#      - run:
#          name: Authenticate to Docker
#          command: echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
#      - run:
#          name: Activate buildx
#          command: |
#                ssh remote-docker \<<EOF
#                sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
#                sudo systemctl restart docker
#                sudo docker info
#                EOF
      - run:
          name: Test buildx
          command: |
              export DOCKER_CLI_EXPERIMENTAL=enabled 
              docker buildx ls

  ubuntu_x64_openssl:
    description: Building and pushing OQS performance testing Docker image on Ubuntu that depend on OQS-OpenSSL
    docker:
      - image: openquantumsafe/ci-ubuntu-focal-x86_64:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - setup_remote_docker
      - run:
          name: Authenticate to Docker
          command: echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
      - run:
          name: Build and test profiling image
          command: |
            # The CircleCI executor offers 35 cores, but using
            # all of them might exhaust memory
            docker build --build-arg MAKE_DEFINES="-j 18" -t oqs-perf . &&
            docker run -it oqs-perf /opt/test/selftest.sh
          working_directory: perf
      - when:
          condition:
            or:
              - equal: [ main, << pipeline.git.branch >> ]
              - equal: [ true, << pipeline.parameters.new_openssl_commit >> ]
          steps:
            - run:
                name: Push all images
                command: |
                  docker tag oqs-perf $TARGETNAME/oqs-perf:latest &&
                  docker push $TARGETNAME/oqs-perf:latest 

workflows:
  version: 2.1
  build:
    jobs:
      #- ubuntu_x64_openssl:
      #    context: openquantumsafe
      - ubuntu_x64_xbuild:
          context: openquantumsafe

